jwt:
  key: ${JWT_SECRET_KEY}
  access-expire-time: ${ACCESS_EXPIRE_TIME}
  refresh-expire-time: ${REFRESH_EXPIRE_TIME}

spring:
  application:
    name: hot-item-collector
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/hot-item-collector
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQLDialect

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: hotitembucket
    region:
      static: ap-northeast-2
    stack:
      auto: false