### 로그인 - 유저1
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "loginId": "user1",
  "password": "passWord12!"
}

> {%
    client.global.set("access_token", response.headers.valueOf("access"));
    client.global.set("refresh_token", response.headers.valueOf("refresh"));
    client.log("access_token : " + client.global.get("access_token"))
%}

### 로그인 유저 2
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "loginId": "user2",
  "password": "passWord123!"
}

> {%
    client.global.set("access_token", response.headers.valueOf("access"));
    client.global.set("refresh_token", response.headers.valueOf("refresh"));
%}

### 채팅방 생성
POST http://localhost:8080/chatroom
Content-Type: application/json
Authorization: {{access_token}}

{
  "sellerId": "2"
}

### 채팅방 리스트 호출
GET http://localhost:8080/chatrooms/list
Content-Type: application/json
Authorization: {{access_token}}

### 채팅방 조회
GET http://localhost:8080/chatroom/c3a6b960-10e9-4343-8225-0bd94ea9f2b8

### 채팅 생성
POST http://localhost:8080/chat/message
Content-Type: application/json
Authorization: {{access_token}}

{
    "roomId": "someone Lee_someone Kim",
    "message": "나는 안녕 한데?"
}

### Create or Get Chat Room
POST http://localhost:8080/chatroom
Content-Type: application/json
Authorization: {{access_token}}

{
  "seller": "nick1"
}

> {% client.global.set("roomId", response.body.roomId); %}

### Send Chat Message
POST http://localhost:8080/pub/chat/message
Content-Type: application/json
Authorization: {{access_token}}

{
  "roomId": "{{roomId}}",
  "message": "Hello, this is a test message"
}

### 채팅 마지막 메시지 호출
PATCH http://localhost:8080/chatroom/last/c3a6b960-10e9-4343-8225-0bd94ea9f2b8
Content-Type: application/json
Authorization: {{access_token}}